### ISSUE TITLE
Display ID of selenium service

### ISSUE THREAD

**Issue by igneel64** [praveenprasannan/wdio-video-recorder#2]
On the settings, we get the host of the selenium or the display ID on the "-i" argument. Are those defaults? If so, where is some documentation  or can this be changed?

**Comment by praveenprasannan** [comment]
Dear @igneel64,

Sorry for a very late response. To answer your question, please do check the below section within `index.js` as I am not 100% sure. 

```
browser.ffmpeg = require('child_process').execFile(
        'ffmpeg',
        [
          '-video_size',
          videoSettings.resolution || '1440x900',
          '-r',
          videoSettings.fps || 15,
          '-f',
          'x11grab',
          '-i',
          settings.selenium_host + (videoSettings.display || ':60'),
          '-pix_fmt',
          videoSettings.pixel_format || 'yuv420p', // yuv420p makes vidoes compatable with Quicktime
          '-loglevel',
          'error',
          file
        ]
```

If you are able to change/fix it, please do make a PR as well as others will get some benefit out of it.

Thank you very much. For now, I will close this.
